version: '3.3'

services:
  xmpp_server:
    image: "tigase/tigase-xmpp-server:latest"
    ports:
      - "5222:5222" #c2s port
      - "8080:8080" #http
    environment:
      - PASSWORD=xxxxxxxxxxxxxxxxxx
  
  app:
    build: ./app
    entrypoint: ./entrypoint.sh
    environment:
      - XMPP_SERVER=xmpp_server
      - XMPP_PASSWORD=xxxxxxxxxxxxxxxxxx
    depends_on:
    - xmpp_server
