version: '3.3'

services:
  xmpp_server:
    image: "prosody/prosody:latest"
    ports:
      - "5222:5222" #c2s port
      - "5347:5347" #XMPP component port
      - "8080:80" #http port
    environment:
      - PASSWORD=xxxxxxxxxxxxxxxxxx
  
  app:
    build: ./app
    entrypoint: ./entrypoint.sh
    environment:
      - XMPP_SERVER='xmpp_server:5222'
      - XMPP_PASSWORD=xxxxxxxxxxxxxxxxxx
    