version: '3.3'

services:
  xmpp_server:
    image: ejabberd/ecs
    restart: unless-stopped
    ports:
      - 5222:5222
      - 5280:5280
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml

  effector:
    build: ./app/agents/effector
    restart: unless-stopped
    environment:
      - XMPP_SERVER=xmpp_server
      - XMPP_PASSWORD=PASSWORD
    depends_on:
      - xmpp_server

  monitor:
    build: ./app/agents/monitor
    restart: unless-stopped
    environment:
      - XMPP_SERVER=xmpp_server
      - XMPP_PASSWORD=PASSWORD
    depends_on:
      - xmpp_server

  sensor:
    build: ./app/agents/sensor
    restart: unless-stopped
    environment:
      - XMPP_SERVER=xmpp_server
      - XMPP_PASSWORD=PASSWORD
    depends_on:
      - xmpp_server

  controller:
    build: ./app/agents/controller
    restart: unless-stopped
    environment:
      - XMPP_SERVER=xmpp_server
      - XMPP_PASSWORD=PASSWORD
    depends_on:
      - xmpp_server