[tool.black]
line-length = 79
fmt = false

[tool.mypy]
python_version = "3.10"
mypy_path = "app/"
disallow_incomplete_defs = true
warn_redundant_casts = true
no_implicit_optional = true
no_implicit_reexport = true
strict_equality = true
namespace_packages = true
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
    "spade.*",
]
ignore_missing_imports = true

[tool.ruff]
extend-exclude = [
    ".venv",
    "data",
]
ignore = [
    "E402",
    "E501",
]
select = [
    "E",
    "F",
    "W",
]


[tool.isort]
profile = "black"
line_length = 79
skip_gitignore = true
multi_line_output = 3
